name: lung-cancer-app

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env             # .env có sẵn MONGODB_CONNECTION_STRING
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - lung-cancer-app
    ports:
      - "5000:5000" 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host
    depends_on:
      - api
    networks:
      - lung-cancer-app
    ports:
      - "5173:5173"

  chatbot:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./ollama:/app
      - ollama_modules:/app/ollama_modules
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api                      # nếu chatbot cần gọi API
    networks:
      - lung-cancer-app
    ports:
      - "8501:8501"

volumes:
  backend_node_modules:
  frontend_node_modules:
  ollama_modules:

networks:
  lung-cancer-app:
    driver: bridge
